admin {
  port = 9060
}

participant {
  name = "local"
  storage = "/tmp/canton-storage"
  node-id = 122084768362d0ce21f1ffec870e55e365a292cdf8f54c5c38ad7775b9bdd462e141

  ledger-api {
    enabled = true
    port = 6865
    auth-jwt-enabled = false

    http {
      enabled = true
      host = "127.0.0.1"
      port = 7575
    }
  }
}
